development:
  adapter: postgresql
  encoding: unicode
  database: telephone_pictionary_dev
  pool: 5
  host: localhost
  username: lisafeatherknee

test:
  adapter: postgresql
  encoding: unicode
  database: telephone_pictionary_test
  pool: 5
  host: localhost
  username: lisafeatherknee

production:
  adapter: postgresql
  encoding: unicode
  database: telephone_pictionary_production
  pool: 5
  username: lisafeatherknee